./OPIM1.1.o-lt -func=0 -gname=orkutminus
./OPIM1.1.o-lt -func=0 -gname=pokecminus
./OPIM1.1.o-lt -func=0 -gname=livejournal
./OPIM1.1.o-lt -func=0 -gname=twitterminusone
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.02 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.03 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.04 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.05 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.06 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.07 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.08 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.09 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.02 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.03 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.04 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.05 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.06 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.07 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.08 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.09 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.02 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.03 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.04 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.05 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.06 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.07 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.08 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.09 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.02 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.03 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.04 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.05 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.06 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.07 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.08 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.09 -alg=opim-c -mode=LT -model=IC -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.02 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.03 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.04 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.05 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.06 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.07 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.08 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.09 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.02 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.03 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.04 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.05 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.06 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.07 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.08 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.09 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.02 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.03 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.04 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.05 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.06 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.07 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.08 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.09 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.02 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.03 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.04 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.05 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.06 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.07 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.08 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.09 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.02 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.03 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.04 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.05 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.06 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.07 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.08 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.09 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.02 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.03 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.04 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.05 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.06 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.07 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.08 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.09 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.02 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.03 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.04 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.05 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.06 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.07 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.08 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.09 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.02 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.03 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.04 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.05 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.06 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.07 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.08 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.09 -model=LT -pdist=WC
