./OPIM1.1.o-lt -func=0 -gname=orkutminus
./OPIM1.1.o-lt -func=0 -gname=pokecminus
./OPIM1.1.o-lt -func=0 -gname=livejournal
./OPIM1.1.o-lt -func=0 -gname=twitterminusone
./radeopim -func=1 -gname=orkutminus -seedsize=1 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=10 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=50 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=150 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=orkutminus -seedsize=200 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=1 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=10 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=50 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=150 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=pokecminus -seedsize=200 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=1 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=10 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=50 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=150 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=livejournal -seedsize=200 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=1 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=10 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=50 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=100 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=150 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./radeopim -func=1 -gname=twitterminusone -seedsize=200 -eps=0.01 -alg=opim-c -mode=LT -model=IC -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=1 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=10 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=50 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=150 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -seedsize=200 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=1 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=10 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=50 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=150 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -seedsize=200 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=1 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=10 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=50 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=150 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -seedsize=200 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=1 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=10 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=50 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=100 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=150 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -seedsize=200 -eps=0.01 -alg=opim-c -mode=1 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=1 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=10 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=50 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=150 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=orkutminus -alg=opim-c -mode=1 -seedsize=200 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=1 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=10 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=50 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=150 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=pokecminus -alg=opim-c -mode=1 -seedsize=200 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=1 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=10 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=50 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=150 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=livejournal -alg=opim-c -mode=1 -seedsize=200 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=1 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=10 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=50 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=100 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=150 -eps=0.01 -model=LT -pdist=WC
./OPIM1.1.o-lt -func=1 -gname=twitterminusone -alg=opim-c -mode=1 -seedsize=200 -eps=0.01 -model=LT -pdist=WC
